services:
  sc_front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    container_name: SC_Front
    ports:
      - '${FRONT_PORT:-3000}:3000'
      - '24678:24678'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      NODE_ENV: development
      NUXT_PUBLIC_API_BASE: '${NUXT_PUBLIC_API_BASE:-http://localhost:8000}'
