#!/bin/bash
set -e

# /tmp/.X11-unix est cree et permissionne au build (le conteneur tourne en nuxt)

if [ $# -gt 0 ]; then
    exec "$@"
else
    # le volume nomme sc_front_node_modules est cree par root au premier montage,
    # il faut le rendre a nuxt avant d'installer les dependances
    sudo chown -R nuxt:nuxt /app/node_modules
    npm install
    exec npm run dev
fi
